import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import { Pool, QueryResultRow } from 'pg';
import { v4 as uuidv4 } from 'uuid';

const DEFAULT_ADMIN = {
  username: 'Havi',
  email: 'havidu6@gmail.com',
  password: '19072006a',
  role: 'admin',
};

const readSupabaseConfig = () => {
  const configPath = path.join(process.cwd(), 'src', 'Backend', 'supabase.txt');
  if (!fs.existsSync(configPath)) return {};

  const content = fs.readFileSync(configPath, 'utf8');
  const projectUrl = content.match(/URL du projet:\s*(.+)/i)?.[1]?.trim();
  const connectionTemplate = content.match(/Chaine de connection.*?:\s*(.+)/i)?.[1]?.trim();
  const poolerTemplate = content.match(/pooler:\s*(.+)/i)?.[1]?.trim();
  const password = content.match(/Mot de pase:\s*(.+)/i)?.[1]?.trim();

  return {
    projectUrl,
    connectionString: (poolerTemplate || connectionTemplate) && password
      ? (poolerTemplate || connectionTemplate)!.replace('[YOUR-PASSWORD]', encodeURIComponent(password))
      : (poolerTemplate || connectionTemplate),
  };
};

const supabaseConfig = readSupabaseConfig();
const connectionString = process.env.SUPABASE_DATABASE_URL || supabaseConfig.connectionString || process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error('DATABASE_URL is missing and src/Backend/supabase.txt has no connection string.');
}

const pool = new Pool({
  connectionString,
  ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false,
});

export const db = {
  async query<T extends QueryResultRow = QueryResultRow>(sql: string, params: unknown[] = []) {
    const result = await pool.query<T>(sql, params);
    return result;
  },

  async one<T extends QueryResultRow = QueryResultRow>(sql: string, params: unknown[] = []) {
    const result = await pool.query<T>(sql, params);
    if (!result.rows[0]) throw new Error('Expected one row, got none.');
    return result.rows[0];
  },

  async maybeOne<T extends QueryResultRow = QueryResultRow>(sql: string, params: unknown[] = []) {
    const result = await pool.query<T>(sql, params);
    return result.rows[0] as T | undefined;
  },

  async many<T extends QueryResultRow = QueryResultRow>(sql: string, params: unknown[] = []) {
    const result = await pool.query<T>(sql, params);
    return result.rows;
  },

  async run(sql: string, params: unknown[] = []) {
    const result = await pool.query(sql, params);
    return {
      changes: result.rowCount ?? 0,
      lastInsertRowid: result.rows[0]?.id,
    };
  },
};

export async function initializeDatabase(): Promise<void> {
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password TEXT NOT NULL,
      username TEXT UNIQUE NOT NULL,
      role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin', 'user')),
      image_url TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS posts (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE NOT NULL,
      content TEXT NOT NULL,
      excerpt TEXT,
      image_url TEXT,
      author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      published BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS files (
      id TEXT PRIMARY KEY,
      filename TEXT NOT NULL,
      original_name TEXT NOT NULL,
      legend TEXT,
      usage TEXT NOT NULL DEFAULT 'gallery',
      categorie TEXT,
      mimetype TEXT NOT NULL,
      size INTEGER NOT NULL,
      uploader_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      is_public BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS refresh_tokens (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token TEXT UNIQUE NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS sermons (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      titre TEXT NOT NULL,
      verset TEXT,
      description TEXT,
      chemin TEXT,
      image_url TEXT,
      date TEXT,
      auteur TEXT,
      categorie TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      titre TEXT NOT NULL,
      lieu TEXT,
      description TEXT,
      image_url TEXT,
      categorie TEXT,
      heure TEXT,
      date TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS contact_messages (
      id TEXT PRIMARY KEY,
      nom TEXT NOT NULL,
      email TEXT NOT NULL,
      sujet TEXT NOT NULL,
      contenu TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS donations (
      id TEXT PRIMARY KEY,
      reference TEXT UNIQUE NOT NULL,
      donor_name TEXT NOT NULL,
      donor_email TEXT NOT NULL,
      donor_phone TEXT NOT NULL,
      amount INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'USD',
      designation TEXT NOT NULL,
      description TEXT,
      status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'paid', 'failed', 'cancelled')),
      provider TEXT NOT NULL DEFAULT 'monetbil',
      provider_transaction_id TEXT,
      provider_payload TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS idx_posts_author ON posts(author_id);
    CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug);
    CREATE INDEX IF NOT EXISTS idx_posts_published ON posts(published);
    CREATE INDEX IF NOT EXISTS idx_files_uploader ON files(uploader_id);
    CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id);
    CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens(token);
    CREATE INDEX IF NOT EXISTS idx_contact_messages_created ON contact_messages(created_at);
    CREATE INDEX IF NOT EXISTS idx_donations_reference ON donations(reference);
    CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);
    CREATE INDEX IF NOT EXISTS idx_donations_created ON donations(created_at);
  `);

  await ensureColumnExists('users', 'image_url', 'TEXT');
  await ensureColumnExists('posts', 'image_url', 'TEXT');
  await ensureColumnExists('sermons', 'image_url', 'TEXT');
  await ensureColumnExists('events', 'image_url', 'TEXT');
  await ensureColumnExists('files', 'legend', 'TEXT');
  await ensureColumnExists('files', 'usage', "TEXT NOT NULL DEFAULT 'gallery'");
  await ensureColumnExists('files', 'categorie', 'TEXT');
  await db.query("UPDATE files SET usage = 'gallery' WHERE usage IS NULL OR usage = ''");
  await ensureDefaultAdmin();

  console.log('# Supabase/Postgres database initialized');
}

async function ensureColumnExists(tableName: string, columnName: string, definition: string): Promise<void> {
  const column = await db.maybeOne(
    `
      SELECT column_name
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2
    `,
    [tableName, columnName]
  );

  if (!column) {
    await db.query(`ALTER TABLE ${tableName} ADD COLUMN ${columnName} ${definition}`);
  }
}

async function ensureDefaultAdmin(): Promise<void> {
  const hashedPassword = await bcrypt.hash(DEFAULT_ADMIN.password, 12);
  const existing = await db.maybeOne<{ id: string }>(
    'SELECT id FROM users WHERE email = $1 OR username = $2',
    [DEFAULT_ADMIN.email, DEFAULT_ADMIN.username]
  );

  if (existing) {
    await db.query(
      `
        UPDATE users
        SET email = $1, username = $2, password = $3, role = $4, updated_at = now()
        WHERE id = $5
      `,
      [DEFAULT_ADMIN.email, DEFAULT_ADMIN.username, hashedPassword, DEFAULT_ADMIN.role, existing.id]
    );
    console.log(`# Default admin ensured: ${DEFAULT_ADMIN.email}`);
    return;
  }

  await db.query(
    `
      INSERT INTO users (id, email, username, password, role)
      VALUES ($1, $2, $3, $4, $5)
    `,
    [uuidv4(), DEFAULT_ADMIN.email, DEFAULT_ADMIN.username, hashedPassword, DEFAULT_ADMIN.role]
  );

  console.log(`# Default admin created: ${DEFAULT_ADMIN.email}`);
}

export function getDb() {
  return db;
}

export default db;
